version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: danielsmanioto
      MONGO_INITDB_ROOT_PASSWORD: danielsmanioto
    ports:
      - 27017:27017
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: danielsmanioto
      ME_CONFIG_MONGODB_ADMINPASSWORD: danielsmanioto
